-- ==============================================
-- MENTORAX - DROP SCRIPT (SQL Server / Azure)
-- Versão V1 - Adaptado do Oracle
-- ==============================================

-- 🔹 DROPS DE TRIGGERS (verifica se existem)
IF OBJECT_ID('TR_AUDITORIA_USUARIO', 'TR') IS NOT NULL DROP TRIGGER TR_AUDITORIA_USUARIO;
IF OBJECT_ID('TR_AUDITORIA_PERFIL', 'TR') IS NOT NULL DROP TRIGGER TR_AUDITORIA_PERFIL;
IF OBJECT_ID('TR_AUDITORIA_MENTORIA', 'TR') IS NOT NULL DROP TRIGGER TR_AUDITORIA_MENTORIA;
IF OBJECT_ID('TR_AUDITORIA_SESSAO_MENTORIA', 'TR') IS NOT NULL DROP TRIGGER TR_AUDITORIA_SESSAO_MENTORIA;
IF OBJECT_ID('TR_AUDITORIA_PLANO_MENTORIA', 'TR') IS NOT NULL DROP TRIGGER TR_AUDITORIA_PLANO_MENTORIA;
IF OBJECT_ID('TR_AUDITORIA_HISTORICO_IA', 'TR') IS NOT NULL DROP TRIGGER TR_AUDITORIA_HISTORICO_IA;
IF OBJECT_ID('TR_AUDITORIA_FEEDBACK', 'TR') IS NOT NULL DROP TRIGGER TR_AUDITORIA_FEEDBACK;

-- 🔹 DROPS DE TABELAS (ordem reversa de dependência)
IF OBJECT_ID('T_MENTORAX_AUDITORIA', 'U') IS NOT NULL DROP TABLE T_MENTORAX_AUDITORIA;
IF OBJECT_ID('T_MENTORAX_FEEDBACK', 'U') IS NOT NULL DROP TABLE T_MENTORAX_FEEDBACK;
IF OBJECT_ID('T_MENTORAX_HISTORICO_IA', 'U') IS NOT NULL DROP TABLE T_MENTORAX_HISTORICO_IA;
IF OBJECT_ID('T_MENTORAX_PLANO_MENTORIA', 'U') IS NOT NULL DROP TABLE T_MENTORAX_PLANO_MENTORIA;
IF OBJECT_ID('T_MENTORAX_SESSAO_MENTORIA', 'U') IS NOT NULL DROP TABLE T_MENTORAX_SESSAO_MENTORIA;
IF OBJECT_ID('T_MENTORAX_MENTORIA', 'U') IS NOT NULL DROP TABLE T_MENTORAX_MENTORIA;
IF OBJECT_ID('T_MENTORAX_PERFIL_PROFISSIONAL', 'U') IS NOT NULL DROP TABLE T_MENTORAX_PERFIL_PROFISSIONAL;
IF OBJECT_ID('T_MENTORAX_USUARIO', 'U') IS NOT NULL DROP TABLE T_MENTORAX_USUARIO;
IF OBJECT_ID('T_MENTORAX_LOG_ERRO', 'U') IS NOT NULL DROP TABLE T_MENTORAX_LOG_ERRO;
GO
