-- =========================================================
-- BANCO DE DADOS: MENTORAX (Tema: Futuro do Trabalho)
-- Modelagem em 3FN - SQL Server / Azure
-- =========================================================

CREATE TABLE T_MENTORAX_USUARIO (
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    NOME NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(150) UNIQUE NOT NULL,
    SENHA_HASH NVARCHAR(255) NOT NULL,
    CARGO NVARCHAR(100),
    TIPO_USUARIO NVARCHAR(20) CHECK (TIPO_USUARIO IN ('MENTOR', 'MENTORADO', 'ADMIN')),
    DATA_CADASTRO DATETIME DEFAULT GETDATE(),
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    CODIGO_RECUPERACAO NVARCHAR(10) NULL,
    CODIGO_RECUPERACAO_EXPIRA_EM DATETIME NULL,
    CODIGO_RECUPERACAO_TENTATIVAS INT DEFAULT 0,
    ULTIMA_RECUPERACAO_EM DATETIME NULL
);
GO

CREATE TABLE T_MENTORAX_PERFIL_PROFISSIONAL (
    ID_PERFIL INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    AREA_INTERESSE NVARCHAR(100),
    OBJETIVOS_PROFISSIONAIS NVARCHAR(500),
    EXPERIENCIA_RESUMIDA NVARCHAR(500),
    SOFT_SKILLS NVARCHAR(300),
    HARD_SKILLS NVARCHAR(300),
    DISPONIBILIDADE_HORAS INT,
    CONSTRAINT FK_PERFIL_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES T_MENTORAX_USUARIO(ID_USUARIO)
        ON DELETE CASCADE
);
GO

CREATE TABLE T_MENTORAX_MENTORIA (
    ID_MENTORIA INT IDENTITY(1,1) PRIMARY KEY,
    ID_MENTOR INT NOT NULL,
    ID_MENTORADO INT NOT NULL,
    DATA_INICIO DATETIME DEFAULT GETDATE(),
    DATA_FIM DATETIME NULL,
    STATUS NVARCHAR(20) CHECK (STATUS IN ('ATIVA','PAUSADA','CONCLUIDA')),
    NOTA_SATISFACAO DECIMAL(3,1) NULL,
    CONSTRAINT FK_MENTORIA_MENTOR FOREIGN KEY (ID_MENTOR)
        REFERENCES T_MENTORAX_USUARIO(ID_USUARIO),
    CONSTRAINT FK_MENTORIA_MENTORADO FOREIGN KEY (ID_MENTORADO)
        REFERENCES T_MENTORAX_USUARIO(ID_USUARIO)
);
GO

CREATE TABLE T_MENTORAX_SESSAO_MENTORIA (
    ID_SESSAO INT IDENTITY(1,1) PRIMARY KEY,
    ID_MENTORIA INT NOT NULL,
    DATA_SESSAO DATETIME DEFAULT GETDATE(),
    ASSUNTO NVARCHAR(150),
    RESUMO_SESSAO NVARCHAR(1000),
    PROXIMOS_PASSOS NVARCHAR(1000),
    HUMOR_DETECTADO NVARCHAR(50),
    CONSTRAINT FK_SESSAO_MENTORIA FOREIGN KEY (ID_MENTORIA)
        REFERENCES T_MENTORAX_MENTORIA(ID_MENTORIA)
        ON DELETE CASCADE
);
GO

CREATE TABLE T_MENTORAX_PLANO_MENTORIA (
    ID_PLANO INT IDENTITY(1,1) PRIMARY KEY,
    ID_MENTORIA INT NOT NULL,
    CRONOGRAMA NVARCHAR(MAX),
    DESCRICAO_GERAL NVARCHAR(1000),
    METAS_OKR NVARCHAR(MAX),
    MENSAGEM_MOTIVACIONAL NVARCHAR(500),
    DATA_GERACAO DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_PLANO_MENTORIA FOREIGN KEY (ID_MENTORIA)
        REFERENCES T_MENTORAX_MENTORIA(ID_MENTORIA)
        ON DELETE CASCADE
);
GO

CREATE TABLE T_MENTORAX_HISTORICO_IA (
    ID_HISTORICO INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    PROMPT_ENVIADO NVARCHAR(MAX),
    RESPOSTA_IA NVARCHAR(MAX),
    DATA_EXECUCAO DATETIME DEFAULT GETDATE(),
    TIPO_GERACAO NVARCHAR(50),
    CONSTRAINT FK_HIST_IA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES T_MENTORAX_USUARIO(ID_USUARIO)
        ON DELETE CASCADE
);
GO

CREATE TABLE T_MENTORAX_FEEDBACK (
    ID_FEEDBACK INT IDENTITY(1,1) PRIMARY KEY,
    ID_SESSAO INT NOT NULL,
    NOTA INT CHECK (NOTA BETWEEN 1 AND 5),
    COMENTARIO NVARCHAR(500),
    CONSTRAINT FK_FEEDBACK_SESSAO FOREIGN KEY (ID_SESSAO)
        REFERENCES T_MENTORAX_SESSAO_MENTORIA(ID_SESSAO)
        ON DELETE CASCADE
);
GO

-- =========================================================
-- AUDITORIA DAS TABELAS
-- =========================================================

CREATE TABLE T_MENTORAX_AUDITORIA (
    ID_AUDITORIA INT IDENTITY(1,1) PRIMARY KEY,
    NOME_TABELA NVARCHAR(100),
    OPERACAO NVARCHAR(20),
    USUARIO_OPERACAO NVARCHAR(100),
    DATA_OPERACAO DATETIME DEFAULT GETDATE(),
    VALOR_ANTIGO NVARCHAR(MAX),
    VALOR_NOVO NVARCHAR(MAX)
);
GO

CREATE TABLE T_MENTORAX_LOG_ERRO (
    ID_LOG INT IDENTITY(1,1) PRIMARY KEY,
    PROCEDURE_NOME NVARCHAR(100) NOT NULL,
    MENSAGEM_ERRO NVARCHAR(4000) NOT NULL,
    DATA_OCORRENCIA DATETIME DEFAULT (GETDATE())
);
GO
