-- =========================================================
-- TRIGGERS DE AUDITORIA MENTORAX (SQL SERVER / AZURE)
-- =========================================================

-- ==========================================
-- TRIGGER: T_MENTORAX_USUARIO
-- ==========================================
CREATE OR ALTER TRIGGER TR_AUDITORIA_USUARIO
ON T_MENTORAX_USUARIO
AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @usuario NVARCHAR(100) = SUSER_SNAME();

    -- INSERT
    IF EXISTS (SELECT 1 FROM INSERTED) AND NOT EXISTS (SELECT 1 FROM DELETED)
    INSERT INTO T_MENTORAX_AUDITORIA (NOME_TABELA, OPERACAO, USUARIO_OPERACAO, VALOR_NOVO)
SELECT 'T_MENTORAX_USUARIO','INSERT',@usuario,
       CONCAT('ID_USUARIO=',I.ID_USUARIO,', NOME=',I.NOME,', EMAIL=',I.EMAIL,', SENHA_HASH=',I.SENHA_HASH,
              ', CARGO=',I.CARGO,', TIPO_USUARIO=',I.TIPO_USUARIO,', DATA_CADASTRO=',FORMAT(I.DATA_CADASTRO,'dd/MM/yyyy HH:mm:ss'),
              ', ATIVO=',I.ATIVO)
FROM INSERTED I;

-- UPDATE
IF EXISTS (SELECT 1 FROM INSERTED) AND EXISTS (SELECT 1 FROM DELETED)
    INSERT INTO T_MENTORAX_AUDITORIA (NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO,VALOR_NOVO)
SELECT 'T_MENTORAX_USUARIO','UPDATE',@usuario,
       CONCAT('ID_USUARIO=',D.ID_USUARIO,', NOME=',D.NOME,', EMAIL=',D.EMAIL,', CARGO=',D.CARGO),
       CONCAT('ID_USUARIO=',I.ID_USUARIO,', NOME=',I.NOME,', EMAIL=',I.EMAIL,', CARGO=',I.CARGO)
FROM INSERTED I INNER JOIN DELETED D ON I.ID_USUARIO=D.ID_USUARIO;

-- DELETE
IF NOT EXISTS (SELECT 1 FROM INSERTED) AND EXISTS (SELECT 1 FROM DELETED)
    INSERT INTO T_MENTORAX_AUDITORIA (NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO)
SELECT 'T_MENTORAX_USUARIO','DELETE',@usuario,
       CONCAT('ID_USUARIO=',D.ID_USUARIO,', NOME=',D.NOME,', EMAIL=',D.EMAIL,', CARGO=',D.CARGO)
FROM DELETED D;
END;
GO

-- ==========================================
-- TRIGGER: T_MENTORAX_PERFIL_PROFISSIONAL
-- ==========================================
CREATE OR ALTER TRIGGER TR_AUDITORIA_PERFIL
ON T_MENTORAX_PERFIL_PROFISSIONAL
AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @usuario NVARCHAR(100)=SUSER_SNAME();

    IF EXISTS(SELECT 1 FROM INSERTED) AND NOT EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_NOVO)
SELECT 'T_MENTORAX_PERFIL_PROFISSIONAL','INSERT',@usuario,
       CONCAT('ID_PERFIL=',I.ID_PERFIL,', ID_USUARIO=',I.ID_USUARIO,', AREA_INTERESSE=',I.AREA_INTERESSE)
FROM INSERTED I;

IF EXISTS(SELECT 1 FROM INSERTED) AND EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO,VALOR_NOVO)
SELECT 'T_MENTORAX_PERFIL_PROFISSIONAL','UPDATE',@usuario,
       CONCAT('ID_PERFIL=',D.ID_PERFIL,', AREA_INTERESSE=',D.AREA_INTERESSE),
       CONCAT('ID_PERFIL=',I.ID_PERFIL,', AREA_INTERESSE=',I.AREA_INTERESSE)
FROM INSERTED I JOIN DELETED D ON I.ID_PERFIL=D.ID_PERFIL;

IF NOT EXISTS(SELECT 1 FROM INSERTED) AND EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO)
SELECT 'T_MENTORAX_PERFIL_PROFISSIONAL','DELETE',@usuario,
       CONCAT('ID_PERFIL=',D.ID_PERFIL,', AREA_INTERESSE=',D.AREA_INTERESSE)
FROM DELETED D;
END;
GO

-- ==========================================
-- TRIGGER: T_MENTORAX_MENTORIA
-- ==========================================
CREATE OR ALTER TRIGGER TR_AUDITORIA_MENTORIA
ON T_MENTORAX_MENTORIA
AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @usuario NVARCHAR(100)=SUSER_SNAME();

    IF EXISTS(SELECT 1 FROM INSERTED) AND NOT EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_NOVO)
SELECT 'T_MENTORAX_MENTORIA','INSERT',@usuario,
       CONCAT('ID_MENTORIA=',I.ID_MENTORIA,', ID_MENTOR=',I.ID_MENTOR,', ID_MENTORADO=',I.ID_MENTORADO,
              ', STATUS=',I.STATUS,', NOTA_SATISFACAO=',I.NOTA_SATISFACAO)
FROM INSERTED I;

IF EXISTS(SELECT 1 FROM INSERTED) AND EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO,VALOR_NOVO)
SELECT 'T_MENTORAX_MENTORIA','UPDATE',@usuario,
       CONCAT('STATUS=',D.STATUS,', NOTA_SATISFACAO=',D.NOTA_SATISFACAO),
       CONCAT('STATUS=',I.STATUS,', NOTA_SATISFACAO=',I.NOTA_SATISFACAO)
FROM INSERTED I JOIN DELETED D ON I.ID_MENTORIA=D.ID_MENTORIA;

IF NOT EXISTS(SELECT 1 FROM INSERTED) AND EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO)
SELECT 'T_MENTORAX_MENTORIA','DELETE',@usuario,
       CONCAT('ID_MENTORIA=',D.ID_MENTORIA,', STATUS=',D.STATUS)
FROM DELETED D;
END;
GO

-- ==========================================
-- TRIGGER: T_MENTORAX_SESSAO_MENTORIA
-- ==========================================
CREATE OR ALTER TRIGGER TR_AUDITORIA_SESSAO_MENTORIA
ON T_MENTORAX_SESSAO_MENTORIA
AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @usuario NVARCHAR(100)=SUSER_SNAME();

    IF EXISTS(SELECT 1 FROM INSERTED) AND NOT EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_NOVO)
SELECT 'T_MENTORAX_SESSAO_MENTORIA','INSERT',@usuario,
       CONCAT('ID_SESSAO=',I.ID_SESSAO,', ASSUNTO=',I.ASSUNTO,', DATA_SESSAO=',FORMAT(I.DATA_SESSAO,'dd/MM/yyyy HH:mm:ss'))
FROM INSERTED I;

IF EXISTS(SELECT 1 FROM INSERTED) AND EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO,VALOR_NOVO)
SELECT 'T_MENTORAX_SESSAO_MENTORIA','UPDATE',@usuario,
       CONCAT('ASSUNTO=',D.ASSUNTO,', RESUMO_SESSAO=',D.RESUMO_SESSAO),
       CONCAT('ASSUNTO=',I.ASSUNTO,', RESUMO_SESSAO=',I.RESUMO_SESSAO)
FROM INSERTED I JOIN DELETED D ON I.ID_SESSAO=D.ID_SESSAO;

IF NOT EXISTS(SELECT 1 FROM INSERTED) AND EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO)
SELECT 'T_MENTORAX_SESSAO_MENTORIA','DELETE',@usuario,
       CONCAT('ID_SESSAO=',D.ID_SESSAO,', ASSUNTO=',D.ASSUNTO)
FROM DELETED D;
END;
GO

-- ==========================================
-- TRIGGER: T_MENTORAX_PLANO_MENTORIA
-- ==========================================
CREATE OR ALTER TRIGGER TR_AUDITORIA_PLANO_MENTORIA
ON T_MENTORAX_PLANO_MENTORIA
AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @usuario NVARCHAR(100)=SUSER_SNAME();

    IF EXISTS(SELECT 1 FROM INSERTED) AND NOT EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_NOVO)
SELECT 'T_MENTORAX_PLANO_MENTORIA','INSERT',@usuario,
       CONCAT('ID_PLANO=',I.ID_PLANO,', DESCRICAO_GERAL=',I.DESCRICAO_GERAL)
FROM INSERTED I;

IF EXISTS(SELECT 1 FROM INSERTED) AND EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO,VALOR_NOVO)
SELECT 'T_MENTORAX_PLANO_MENTORIA','UPDATE',@usuario,
       CONCAT('DESCRICAO_GERAL=',D.DESCRICAO_GERAL),
       CONCAT('DESCRICAO_GERAL=',I.DESCRICAO_GERAL)
FROM INSERTED I JOIN DELETED D ON I.ID_PLANO=D.ID_PLANO;

IF NOT EXISTS(SELECT 1 FROM INSERTED) AND EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO)
SELECT 'T_MENTORAX_PLANO_MENTORIA','DELETE',@usuario,
       CONCAT('ID_PLANO=',D.ID_PLANO,', DESCRICAO_GERAL=',D.DESCRICAO_GERAL)
FROM DELETED D;
END;
GO

-- ==========================================
-- TRIGGER: T_MENTORAX_HISTORICO_IA
-- ==========================================
CREATE OR ALTER TRIGGER TR_AUDITORIA_HISTORICO_IA
ON T_MENTORAX_HISTORICO_IA
AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @usuario NVARCHAR(100)=SUSER_SNAME();

    IF EXISTS(SELECT 1 FROM INSERTED) AND NOT EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_NOVO)
SELECT 'T_MENTORAX_HISTORICO_IA','INSERT',@usuario,
       CONCAT('ID_HISTORICO=',I.ID_HISTORICO,', TIPO_GERACAO=',I.TIPO_GERACAO)
FROM INSERTED I;

IF EXISTS(SELECT 1 FROM INSERTED) AND EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO,VALOR_NOVO)
SELECT 'T_MENTORAX_HISTORICO_IA','UPDATE',@usuario,
       CONCAT('TIPO_GERACAO=',D.TIPO_GERACAO),
       CONCAT('TIPO_GERACAO=',I.TIPO_GERACAO)
FROM INSERTED I JOIN DELETED D ON I.ID_HISTORICO=D.ID_HISTORICO;

IF NOT EXISTS(SELECT 1 FROM INSERTED) AND EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO)
SELECT 'T_MENTORAX_HISTORICO_IA','DELETE',@usuario,
       CONCAT('ID_HISTORICO=',D.ID_HISTORICO,', TIPO_GERACAO=',D.TIPO_GERACAO)
FROM DELETED D;
END;
GO

-- ==========================================
-- TRIGGER: T_MENTORAX_FEEDBACK
-- ==========================================
CREATE OR ALTER TRIGGER TR_AUDITORIA_FEEDBACK
ON T_MENTORAX_FEEDBACK
AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @usuario NVARCHAR(100)=SUSER_SNAME();

    IF EXISTS(SELECT 1 FROM INSERTED) AND NOT EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_NOVO)
SELECT 'T_MENTORAX_FEEDBACK','INSERT',@usuario,
       CONCAT('ID_FEEDBACK=',I.ID_FEEDBACK,', NOTA=',I.NOTA,', COMENTARIO=',I.COMENTARIO)
FROM INSERTED I;

IF EXISTS(SELECT 1 FROM INSERTED) AND EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO,VALOR_NOVO)
SELECT 'T_MENTORAX_FEEDBACK','UPDATE',@usuario,
       CONCAT('NOTA=',D.NOTA,', COMENTARIO=',D.COMENTARIO),
       CONCAT('NOTA=',I.NOTA,', COMENTARIO=',I.COMENTARIO)
FROM INSERTED I JOIN DELETED D ON I.ID_FEEDBACK=D.ID_FEEDBACK;

IF NOT EXISTS(SELECT 1 FROM INSERTED) AND EXISTS(SELECT 1 FROM DELETED)
        INSERT INTO T_MENTORAX_AUDITORIA(NOME_TABELA,OPERACAO,USUARIO_OPERACAO,VALOR_ANTIGO)
SELECT 'T_MENTORAX_FEEDBACK','DELETE',@usuario,
       CONCAT('ID_FEEDBACK=',D.ID_FEEDBACK,', NOTA=',D.NOTA,', COMENTARIO=',D.COMENTARIO)
FROM DELETED D;
END;
GO