-- =========================================================
-- PROCEDURES DE INSERÇÃO MENTORAX (SQL SERVER / AZURE)
-- =========================================================

-- Procedure: Inserir Usuário
CREATE OR ALTER PROCEDURE PRC_INS_USUARIO
    @P_NOME NVARCHAR(100),
    @P_EMAIL NVARCHAR(150),
    @P_SENHA_HASH NVARCHAR(255),
    @P_CARGO NVARCHAR(100),
    @P_TIPO_USUARIO NVARCHAR(20),
    @P_ATIVO CHAR(1) = 'S',
    @O_ID_USUARIO INT OUTPUT
    AS
BEGIN
    SET NOCOUNT ON;
BEGIN TRY
INSERT INTO T_MENTORAX_USUARIO (NOME, EMAIL, SENHA_HASH, CARGO, TIPO_USUARIO, ATIVO)
        VALUES (@P_NOME, @P_EMAIL, @P_SENHA_HASH, @P_CARGO, @P_TIPO_USUARIO, @P_ATIVO);

        SET @O_ID_USUARIO = SCOPE_IDENTITY();
END TRY
BEGIN CATCH
INSERT INTO T_MENTORAX_LOG_ERRO (PROCEDURE_NOME, MENSAGEM_ERRO)
        VALUES ('PRC_INS_USUARIO', ERROR_MESSAGE());
        THROW;
END CATCH
END;
GO