-- =========================================================
-- PROCEDURES DE INSERÇÃO MENTORAX (SQL SERVER / AZURE)
-- =========================================================

-- Procedure: Inserir Perfil Profissional
CREATE OR ALTER PROCEDURE PRC_INS_PERFIL
    @P_ID_USUARIO INT,
    @P_AREA NVARCHAR(100),
    @P_OBJ NVARCHAR(500),
    @P_EXP NVARCHAR(500),
    @P_SOFT NVARCHAR(300),
    @P_HARD NVARCHAR(300),
    @P_DISP_HORAS INT,
    @O_ID_PERFIL INT OUTPUT
    AS
BEGIN
    SET NOCOUNT ON;
BEGIN TRY
INSERT INTO T_MENTORAX_PERFIL_PROFISSIONAL
        (ID_USUARIO, AREA_INTERESSE, OBJETIVOS_PROFISSIONAIS, EXPERIENCIA_RESUMIDA, SOFT_SKILLS, HARD_SKILLS, DISPONIBILIDADE_HORAS)
        VALUES (@P_ID_USUARIO, @P_AREA, @P_OBJ, @P_EXP, @P_SOFT, @P_HARD, @P_DISP_HORAS);

        SET @O_ID_PERFIL = SCOPE_IDENTITY();
END TRY
BEGIN CATCH
INSERT INTO T_MENTORAX_LOG_ERRO (PROCEDURE_NOME, MENSAGEM_ERRO)
        VALUES ('PRC_INS_PERFIL', ERROR_MESSAGE());
        THROW;
END CATCH
END;
GO