-- =========================================================
-- PROCEDURES DE INSERÇÃO MENTORAX (SQL SERVER / AZURE)
-- =========================================================

-- Procedure: Inserir Mentoria
CREATE OR ALTER PROCEDURE PRC_INS_MENTORIA
    @P_ID_MENTOR INT,
    @P_ID_MENTORADO INT,
    @P_DATA_INICIO DATETIME = NULL,
    @P_DATA_FIM DATETIME = NULL,
    @P_STATUS NVARCHAR(20),
    @P_NOTA DECIMAL(3,1),
    @O_ID_MENTORIA INT OUTPUT
    AS
BEGIN
    SET NOCOUNT ON;

    IF @P_DATA_INICIO IS NULL
        SET @P_DATA_INICIO = GETDATE();

BEGIN TRY
INSERT INTO dbo.T_MENTORAX_MENTORIA
            (ID_MENTOR, ID_MENTORADO, DATA_INICIO, DATA_FIM, STATUS, NOTA_SATISFACAO)
        VALUES
            (@P_ID_MENTOR, @P_ID_MENTORADO, @P_DATA_INICIO, @P_DATA_FIM, @P_STATUS, @P_NOTA);

        SET @O_ID_MENTORIA = SCOPE_IDENTITY();
END TRY
BEGIN CATCH
INSERT INTO dbo.T_MENTORAX_LOG_ERRO (PROCEDURE_NOME, MENSAGEM_ERRO)
        VALUES ('PRC_INS_MENTORIA', ERROR_MESSAGE());
        THROW;
END CATCH
END;
GO
