-- =========================================================
-- PROCEDURES DE INSERÇÃO MENTORAX (SQL SERVER / AZURE)
-- =========================================================

-- Procedure: Inserir Sessão de Mentoria
CREATE OR ALTER PROCEDURE PRC_INS_SESSAO
    @P_ID_MENTORIA INT,
    @P_DATA_SESSAO DATETIME = NULL,
    @P_ASSUNTO NVARCHAR(150),
    @P_RESUMO NVARCHAR(1000),
    @P_PROX NVARCHAR(1000),
    @P_HUMOR NVARCHAR(50),
    @O_ID_SESSAO INT OUTPUT
    AS
BEGIN
    SET NOCOUNT ON;

    IF @P_DATA_SESSAO IS NULL
        SET @P_DATA_SESSAO = GETDATE();

BEGIN TRY
INSERT INTO T_MENTORAX_SESSAO_MENTORIA
        (ID_MENTORIA, DATA_SESSAO, ASSUNTO, RESUMO_SESSAO, PROXIMOS_PASSOS, HUMOR_DETECTADO)
        VALUES (@P_ID_MENTORIA, @P_DATA_SESSAO, @P_ASSUNTO, @P_RESUMO, @P_PROX, @P_HUMOR);

        SET @O_ID_SESSAO = SCOPE_IDENTITY();
END TRY
BEGIN CATCH
INSERT INTO T_MENTORAX_LOG_ERRO (PROCEDURE_NOME, MENSAGEM_ERRO)
        VALUES ('PRC_INS_SESSAO', ERROR_MESSAGE());
        THROW;
END CATCH
END;
GO