-- =========================================================
-- PROCEDURES DE INSERÇÃO MENTORAX (SQL SERVER / AZURE)
-- =========================================================

-- Procedure: Inserir Plano de Mentoria
CREATE OR ALTER PROCEDURE PRC_INS_PLANO
    @P_ID_MENTORIA INT,
    @P_CRONOGRAMA NVARCHAR(MAX),
    @P_DESC NVARCHAR(1000),
    @P_OKRS NVARCHAR(MAX),
    @P_MSG NVARCHAR(500),
    @P_DATA_GERACAO DATETIME = NULL,
    @O_ID_PLANO INT OUTPUT
    AS
BEGIN
    SET NOCOUNT ON;

    IF @P_DATA_GERACAO IS NULL
        SET @P_DATA_GERACAO = GETDATE();

BEGIN TRY
INSERT INTO T_MENTORAX_PLANO_MENTORIA
        (ID_MENTORIA, CRONOGRAMA, DESCRICAO_GERAL, METAS_OKR, MENSAGEM_MOTIVACIONAL, DATA_GERACAO)
        VALUES (@P_ID_MENTORIA, @P_CRONOGRAMA, @P_DESC, @P_OKRS, @P_MSG, @P_DATA_GERACAO);

        SET @O_ID_PLANO = SCOPE_IDENTITY();
END TRY
BEGIN CATCH
INSERT INTO T_MENTORAX_LOG_ERRO (PROCEDURE_NOME, MENSAGEM_ERRO)
        VALUES ('PRC_INS_PLANO', ERROR_MESSAGE());
        THROW;
END CATCH
END;
GO