-- =========================================================
-- PROCEDURES DE INSERÇÃO MENTORAX (SQL SERVER / AZURE)
-- =========================================================

-- Procedure: Inserir Histórico IA
CREATE OR ALTER PROCEDURE PRC_INS_HIST_IA
    @P_ID_USUARIO INT,
    @P_PROMPT NVARCHAR(MAX),
    @P_RESPOSTA NVARCHAR(MAX),
    @P_DATA_EXEC DATETIME = NULL,
    @P_TIPO NVARCHAR(50),
    @O_ID_HIST INT OUTPUT
    AS
BEGIN
    SET NOCOUNT ON;

    IF @P_DATA_EXEC IS NULL
        SET @P_DATA_EXEC = GETDATE();

BEGIN TRY
INSERT INTO T_MENTORAX_HISTORICO_IA
        (ID_USUARIO, PROMPT_ENVIADO, RESPOSTA_IA, DATA_EXECUCAO, TIPO_GERACAO)
        VALUES (@P_ID_USUARIO, @P_PROMPT, @P_RESPOSTA, @P_DATA_EXEC, @P_TIPO);

        SET @O_ID_HIST = SCOPE_IDENTITY();
END TRY
BEGIN CATCH
INSERT INTO T_MENTORAX_LOG_ERRO (PROCEDURE_NOME, MENSAGEM_ERRO)
        VALUES ('PRC_INS_HIST_IA', ERROR_MESSAGE());
        THROW;
END CATCH
END;
GO