-- =========================================================
-- PROCEDURES DE INSERÇÃO MENTORAX (SQL SERVER / AZURE)
-- =========================================================

-- Procedure: Inserir Feedback
CREATE OR ALTER PROCEDURE PRC_INS_FEEDBACK
    @P_ID_SESSAO INT,
    @P_NOTA INT,
    @P_COMENTARIO NVARCHAR(500),
    @O_ID_FEEDBACK INT OUTPUT
    AS
BEGIN
    SET NOCOUNT ON;
BEGIN TRY
INSERT INTO T_MENTORAX_FEEDBACK (ID_SESSAO, NOTA, COMENTARIO)
        VALUES (@P_ID_SESSAO, @P_NOTA, @P_COMENTARIO);

        SET @O_ID_FEEDBACK = SCOPE_IDENTITY();
END TRY
BEGIN CATCH
INSERT INTO T_MENTORAX_LOG_ERRO (PROCEDURE_NOME, MENSAGEM_ERRO)
        VALUES ('PRC_INS_FEEDBACK', ERROR_MESSAGE());
        THROW;
END CATCH
END;
GO