-- Aumentar limites das colunas da tabela T_MENTORAX_PLANO_MENTORIA
-- para permitir planos de mentoria mais completos gerados pela IA

ALTER TABLE T_MENTORAX_PLANO_MENTORIA
ALTER COLUMN MENSAGEM_MOTIVACIONAL NVARCHAR(2000);

ALTER TABLE T_MENTORAX_PLANO_MENTORIA
ALTER COLUMN DESCRICAO_GERAL NVARCHAR(3000);

